### ISSUE TITLE
Can not connekt to ip interface

### ISSUE THREAD

**Issue by ChriD** [KONNEKTING/KonnektingSuite#51]
Hi,
I get following error when using the suite. 
When i click "search", it will find the KNX-Tunneling Interface and i can select ist

`2018-06-12 19:58:19.391 INFO [AWT-EventQueue-0] de.konnekting.suite.SettingsDialog.ipRoutingAutodetectButtonActionPerformed: Selected knxconnection: [TUNNELING]  Gira KNX/IP-Schnittstelle - 10.0.0.1 (MAC: 00:0a:b3:27:55:0d)`

But It cant connect to the IP-Interface. 
```
KONNEKTING Suite - Version 1.0.0-BETA4 Build 2016-10-10_18-18-18 DEBUG MODE!
Betriebssystem: Windows 10
KNX Verbindung: IP-Interface: 1.0.254@10.0.0.1
Fehler beim Öffnen der KNX Verbindung: TUNNELING
de.root1.slicknx.KnxException: Error connecting to KNX: on connect to /10.0.0.1:3671
	at de.root1.slicknx.Knx.<init>(Knx.java:308)
	at de.konnekting.suite.Main.connectKnx(Main.java:247)
	at de.konnekting.suite.Main.access$100(Main.java:77)
	at de.konnekting.suite.Main$2.run(Main.java:169)
	at java.lang.Thread.run(Thread.java:745)
	at de.konnekting.suite.BackgroundTask$1.run(BackgroundTask.java:59)
Caused by: tuwien.auto.calimero.exception.KNXException: on connect to /10.0.0.1:3671
	at tuwien.auto.calimero.knxnetip.ClientConnection.connect(ClientConnection.java:173)
	at tuwien.auto.calimero.knxnetip.KNXnetIPTunnel.<init>(KNXnetIPTunnel.java:131)
	at tuwien.auto.calimero.link.KNXNetworkLinkIP.<init>(KNXNetworkLinkIP.java:142)
	at tuwien.auto.calimero.link.KNXNetworkLinkIP.<init>(KNXNetworkLinkIP.java:180)
	at de.root1.slicknx.Knx.<init>(Knx.java:301)
	... 5 more
Caused by: java.net.SocketException: Network is unreachable: Datagram send failed
	at java.net.DualStackPlainDatagramSocketImpl.socketSend(Native Method)
	at java.net.DualStackPlainDatagramSocketImpl.send(DualStackPlainDatagramSocketImpl.java:136)
	at java.net.DatagramSocket.send(DatagramSocket.java:693)
	at tuwien.auto.calimero.knxnetip.ClientConnection.connect(ClientConnection.java:158)
```

The interface works well in ETS5
Not sure what causes the problem.
Maybe its because i do have several network interfaces,  but as i can see in the log it seems that it ill take the correct one. 
I even tried to disable the firewall. Did not help either.

Any suggestions? Did i miss something?

**Comment by Adminius** [comment]
an IP Interface should allow up 5 connection, but they need to be allowed by user (see user manual).
Are you sure that you already done this?

**Comment by tuxedo0801** [comment]
did you try to "detect" the interface by the suite?

**Comment by ChriD** [comment]
Yes. The suite does find the interface and i can select it. See first log of first post.

But i am not aware of how to allow multiple connections. There is no setting for this and the user manual which was sent with the device does not mention anything like that.
I'll check the online manual in detail but as i remember there were'nt any infos about that either.

**Comment by ChriD** [comment]
I've looked up the technical documentation for my ip interface
http://download.gira.de/data3/21683310.pdf

It says
`Unterstützung von bis zu 4 parallelen KNXnet/IP Tunneling Verbindungen`
But there is no info how to activate those. I think they are activated anyway.

Next try was to et a fixed IP for the interface and to reprogramm it via ETS
ETS again can connect to the interface. No connection via the suite.

One question.
Which Physical Address do i have to enter in the Suite Settings? The "HOST Physical Address" or the "Physical Address" of the interface. I tried both and none of them worked.

I even tried another Application for the IP Interface due there a two versions. But one version can not be programmed to the device

**Comment by ChriD** [comment]
Ich hab das Problem gefunden.
Wie im Eingangspost bereits vermutet hängt es mit multiplen Netzwerkadaptern am host zusammen.
Ich habe nun alle netzwerkadapter deaktiviert außer mein WLAN-adapter und jetzt funktioniert es.

Ich denke da muss noch etwas in der Suite nachgeschärft werden welchen Adapter er benutzt?

**Comment by tuxedo0801** [comment]
Can you pls. post your complete routing table?

On windows, this should be "route print" in a command shell.

br,
Alex

**Comment by ChriD** [comment]
Here is the table with all adapters enabled.
I have to disable all except the wireless one to get the suite to find the interface.

```
===========================================================================
Schnittstellenliste
 11...00 90 f5 eb 3f 92 ......Controller der Familie Realtek PCIe GBE
 19...fe 15 21 0e 92 ee ......Hyper-V Virtual Ethernet Adapter
  3...0a 00 27 00 00 03 ......VirtualBox Host-Only Ethernet Adapter
 18...1e 84 dc 03 b8 6f ......Virtueller Microsoft-Adapter für direktes WiFi
 15...00 ff 92 5e a0 6f ......Kaspersky Security Data Escort Adapter
 12...0c 84 dc 03 b8 6f ......Killer Wireless-N 1202 (2.4GHz and 5GHz)
  1...........................Software Loopback Interface 1
  6...00 00 00 00 00 00 00 e0 Microsoft Teredo Tunneling Adapter
===========================================================================

IPv4-Routentabelle
===========================================================================
Aktive Routen:
     Netzwerkziel    Netzwerkmaske          Gateway    Schnittstelle Metrik
          0.0.0.0          0.0.0.0       10.0.0.138         10.0.0.6     40
         10.0.0.0    255.255.255.0   Auf Verbindung          10.0.0.6    296
         10.0.0.6  255.255.255.255   Auf Verbindung          10.0.0.6    296
       10.0.0.255  255.255.255.255   Auf Verbindung          10.0.0.6    296
        127.0.0.0        255.0.0.0   Auf Verbindung         127.0.0.1    331
        127.0.0.1  255.255.255.255   Auf Verbindung         127.0.0.1    331
  127.255.255.255  255.255.255.255   Auf Verbindung         127.0.0.1    331
     192.168.56.0    255.255.255.0   Auf Verbindung      192.168.56.1    281
     192.168.56.1  255.255.255.255   Auf Verbindung      192.168.56.1    281
   192.168.56.255  255.255.255.255   Auf Verbindung      192.168.56.1    281
        224.0.0.0        240.0.0.0   Auf Verbindung         127.0.0.1    331
        224.0.0.0        240.0.0.0   Auf Verbindung          10.0.0.6    296
        224.0.0.0        240.0.0.0   Auf Verbindung      192.168.56.1    281
  255.255.255.255  255.255.255.255   Auf Verbindung         127.0.0.1    331
  255.255.255.255  255.255.255.255   Auf Verbindung          10.0.0.6    296
  255.255.255.255  255.255.255.255   Auf Verbindung      192.168.56.1    281
===========================================================================
Ständige Routen:
  Keine

IPv6-Routentabelle
===========================================================================
Aktive Routen:
 If Metrik Netzwerkziel             Gateway
  6    331 ::/0                     Auf Verbindung
  1    331 ::1/128                  Auf Verbindung
  6    331 2001::/32                Auf Verbindung
  6    331 2001:0:9d38:953c:487:eb9:3d9f:e416/128
                                    Auf Verbindung
 12    296 fe80::/64                Auf Verbindung
  6    331 fe80::/64                Auf Verbindung
  3    281 fe80::/64                Auf Verbindung
  6    331 fe80::487:eb9:3d9f:e416/128
                                    Auf Verbindung
 12    296 fe80::ac09:d13a:8990:ab00/128
                                    Auf Verbindung
  3    281 fe80::e972:94a5:2891:ea88/128
                                    Auf Verbindung
  1    331 ff00::/8                 Auf Verbindung
 12    296 ff00::/8                 Auf Verbindung
  6    331 ff00::/8                 Auf Verbindung
  3    281 ff00::/8                 Auf Verbindung
===========================================================================
Ständige Routen:
  Keine


```

**Comment by tuxedo0801** [comment]
Found the root-cause:

Calimero is establishing the UDP connection to the KNX Interface with explicitly specifying the local endpoint of the connection:

![image](https://user-images.githubusercontent.com/2862906/41371310-35aba5ee-6f4a-11e8-81f8-f90b4dd341d0.png)

And on my company laptop (where I also have a lot of network interfaces and where I can reproduce the issue), the hostname somehow resolves to an IP that is not from the current used network.

Solvin this issue would mean:

Either convince the calimero core developer to change the implementation to NOT use local endpoint (and let the OS decide on this), or to fix the hostname resolution to the correct address. At least from what java does with name resolution.

All in all: Working on it ...

**Comment by tuxedo0801** [comment]
I think I fixed it for the upxoming suite beta5.

I switched to calimero-core 2.4-rc1, adapted our slicKnx library (that eases KNX access), and tested.

Works now on my laptop. Calimero now searches for an local endpoint that matches the remote endpoint (KNX interface IP).

**Comment by ChriD** [comment]
Thank you!  Ill check it when it's available
